# Generated by Django 4.2.11 on 2025-04-27 17:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='annotation',
            name='annotations_permali_ed58b8_idx',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='annotation',
            name='version',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='annotation',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='permalink',
            field=models.URLField(),
        ),
    ]
